config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :accounts, controllers: {
    sessions: 'accounts/sessions',
    passwords: 'accounts/passwords',
    registrations: 'accounts/registrations',
    confirmations: 'accounts/confirmations'

  }
  namespace :admins do
    get '/', to: 'admins#index'
    get 'status', to: 'admins#status'
    post 'de_activate/:account_id', to: 'admins#de_activate', as: :admins_de_activate
    post 'activate/:account_id', to: 'admins#activate', as: :admins_activate
  end

  get 'accounts/confirmation_pending', to: 'profiles#after_registration_path'
  get 'accounts/after_confirmation', to: 'profiles#after_confirmation_path'
  post 'profiles/search', to: 'profiles#search'
  get 'profiles/status', to: 'profiles#change_status'
  root to: 'homes#index'
  resources :profiles, only: %i[new create index edit show update] do
    member do
      get '/friendships/follow', to: 'friendships#follow'
      get 'friendships/unfollow', to: 'friendships#unfollow'
    end
  end
  get '/archives', to: "posts#archives"
  resources :posts, only: %i[new create edit update] do
    member do
      post '/share', to: 'posts#share'
      get '/archive_post', to: 'posts#archive_post'
      get '/un_archive_post', to: 'posts#un_archive_post'
      post '/likes/un_like', to: 'likes#un_like'
      post 'likes/like', to: 'likes#like'
    end
    resources :comments, :likes, shallow: true
  end
  delete '/posts/destroy', to: 'posts#destroy'
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord

  enum status: { public_profile: 0, private_profile: 1 }

  has_one :archive, dependent: :destroy
  has_one_attached :profile_picture

  has_many :posts, dependent: :destroy
  has_many :followed_profiles, foreign_key: :followed_id, class_name: 'Friendship'
  has_many :followed, through: :followed_profiles, dependent: :destroy
  has_many :follower_profiles, foreign_key: :follower_id, class_name: 'Friendship'
  has_many :follower, through: :follower_profiles, dependent: :destroy

  scope :account_has_profile, ->(a) { where(account_id: a) }
  scope :following, ->(a) { Friendship.where(follower_id: a).pluck(:followed_id) }
  scope :followers, ->(a) { Friendship.where(followed_id: a).pluck(:follower_id) }
  scope :following_count, ->(a) { Friendship.where(follower_id: a).pluck(:followed_id).count }
  scope :followers_count, ->(a) { Friendship.where(followed_id: a).pluck(:follower_id).count }
  scope :max_followers, -> { Friendship.select(:followed_id).group(:followed_id).limit(10) }
  scope :post_count, ->(a) { Post.where(profile_id: a).count }
  scope :likes_count, ->(post) { Like.where(post_id: post).count }
  scope :comments_count, ->(post) { Comment.where(post_id: post).count }

end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  include CurrentProfile
  include ProfilePicture
  include AvatarCreator
  before_action :restrict_admin
  before_action :check_activation_status
  skip_before_action :authenticate_account!, only: %i[after_registration_path after_confirmation_path]
  skip_before_action :verify_authenticity_token, only: [:search]
  skip_before_action :check_activation_status, only: %i[after_registration_path after_confirmation_path]
  skip_before_action :restrict_admin, only: %i[after_registration_path after_confirmation_path]

  layout 'flow', only: [:new,:edit]

  def index
    if !Profile.account_has_profile(current_account.id).exists?
      redirect_to new_profile_path
    else
      @current_profile_picture = current_profile_picture
      @profile = Profile.find_by(account_id: current_account.id)
      @posts = Post.where(profile_id: current_profile).where(archived:0).order(created_at: :desc)
      @followers = Profile.followers_count(@profile.id)
      @following = Profile.following_count(@profile.id)
      @post_count = Profile.post_count(@profile.id)
    end
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.update(email: current_account.email, account_id: current_account.id)
    if @profile.save
      name_creator unless @profile.profile_picture.representable?
      respond_to do |format|
        format.html { redirect_to profiles_path, notice: 'Post was successfully Created.' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @current_profile=Profile.find_by(id:current_profile)
    @current_profile_picture = current_profile_picture
    profile_id = params[:id]
    @profile = Profile.find_by(id: profile_id)
    @followers = Profile.followers_count(profile_id)
    @following = Profile.following_count(profile_id)
    @post_count = Profile.post_count(profile_id)
    follow_check = Friendship.where(follower_id: current_profile).where(followed_id: profile_id)
    followed_id = follow_check.pluck(:followed_id)
    @has_followed = if follow_check.empty?
                      0
                    elsif profile_id.to_i == followed_id[0]
                      1
                    else
                      0
                    end

    if profile_id.to_i == current_profile
      redirect_to profiles_path
    elsif @profile.public_profile?
      @posts = Post.where(profile_id:).order(created_at: :desc)
    elsif @profile.private_profile? && @has_followed == 1
      @posts = Post.where(profile_id:).order(created_at: :desc)
    else
      @message = 'This account is private'
    end
  end

  def edit
    @profile=Profile.find_by(id:params[:id])
  end

  def update
    @profile=Profile.find_by(id:params[:id])
    @profile.update(profile_params)
    @profile.update(email: current_account.email, account_id: current_account.id)
    @profile.update(status:0)
    if @profile.save

      name_creator unless @profile.profile_picture.representable?

      respond_to do |format|
        format.html { redirect_to profiles_path, notice: 'Post was successfully Created.' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def search
    @current_profile = Profile.find_by(id:current_profile)
    @current_profile_picture = current_profile_picture
    @result = if params[:searchQuery].include? '@'
                Profile.where("email LIKE ?",Profile.sanitize_sql_like("#{params[:searchQuery]}"))
              else
                Profile.where("user_name LIKE ?",Profile.sanitize_sql_like("%","#{params[:searchQuery].capitalize}"+"%"))
              end
  end

  def change_status
    profile = Profile.find_by(id:params[:profile_id])
    if profile.public_profile?
        profile.update(status:1)
        respond_to do |format|
          format.json {render json: profile}
        end
    else
      profile.update(status:0)
      respond_to do |format|
        format.json {render json: profile}
      end
    end
  end

  def after_registration_path
    render layout: 'flow'
  end

  def after_confirmation_path
    render layout: 'flow'
  end

  private

  def profile_params
    params.require(:profile).permit(:user_name, :profile_picture)
  end
end

app/views/profiles/after_confirmation_path.html.erb
<div class="main">
  <div class="container">
    <h2>Set your Password</h2>

      <div id="passwordSetup">
        <%= form_for(:format, as: :account, url: account_password_path, html: { method: :PATCH }) do |f| %>
        <%= hidden_field_tag :reset_password_token,params[:reset_password_token] %>
        <%= hidden_field_tag :id,params[:format] %>
        <div class="row">
          <div class="field">
         <div>
           <%="Minimum Password Length: 6 characters"%>
         </div>
          <%= f.label :password, "New password" %>
          <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %>
          <%= f.password_field :password, autofocus: true, autocomplete: "new-password",class: 'form-control' %>
        </div>
        </div>

       <div class="row">
         <div class="field">
          <%= f.label :password_confirmation, "Confirm new password" %>
          <%= f.password_field :password_confirmation, autocomplete: "new-password",class: 'form-control'  %>
        </div>
       </div>

       <div class="row">
         <div class="actions">
          <%= f.submit "Set password" ,class:"btn btn-primary" %>
        </div>
       </div>
      <% end %>

      </div>

  </div>
</div>
<style>
   .main{
    margin-top: 40px;
  }
</style>

app/views/profiles/after_registration_path.html.erb
<div class="main">
  <div class="container">
    <div class="card">
        <div class="card-header">
          Confirmation
        </div>
        <div class="card-body">
          <h5 class="card-title">Confirmation Pending</h5>
          <p class="card-text">Confirm you email by clicking on the link sent to your email</p>
        </div>
      </div>
  </div>
</div>
<style>
  .main
  {
    z-index: 1;
    display: block;
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    padding: 20px;
    border-radius: 5px;
    box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
    height: 200px;
    width: 500px;
  }
</style>

app/views/profiles/edit.html.erb
<div class="main">
    <div class="container">
        <h1>Create New Profile</h1>
            <div id="createProfile">
                <%=form_with model: @profile do |form| %>
                <%=form.label :user_name%>
                <%=form.text_field :user_name%>
                <%=form.label :profile_picture%>
                <%=form.file_field :profile_picture%>
                <%=form.submit%>
                 <%end%>
            </div>
    </div>
</div>
<style>
    .main{
    margin-top: 40px;
    }
    #createProfile
    {
        z-index: 1;
        display: block;
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.2);
        background-color: #91C8E4;
        height: 300px;
        width: max-content;
    }
</style>

app/views/profiles/index.html.erb
<div class="main">
  <div class="container">
    <div class="d-flex justify-content-end mb-3">
      <%=link_to  "Create a New Post",new_post_path,data:{turbo_frame: "modal"},class:"btn btn-primary" ,id:"createPost"%>
      <%=link_to "Archived Posts",archives_path,class:"btn btn-outline-danger",id:"archived"%>
    </div>
    <%=image_tag @profile.profile_picture.representation(resize_to_limit: [500, 500]),class: "post_img"%>
    <h1>Welcome <%=@profile.user_name%></h1>
      <div id="info">
        <%=link_to "Followers: #{@followers}",new_post_path,data:{turbo_frame: "modal"},class:"btn btn primary"%>
        <%=link_to "Following: #{@following}",new_post_path,data:{turbo_frame: "modal"},class:"btn btn primary"%>
        <%# <span>Posts: <span id="postCount"><%=@post_count</span> </span>%>
      </div>
      <div class="modal" id="exampleModal">
        <div id="ModalPostId"></div>
          <div id="editBtn" class="btn btn-primary" >Edit Post</div>
          <a data-turbo-frame="editModal" class="btn btn-primary" id="editPost"></a>
          <div id="deleteBtn" class="btn btn-danger" >Delete Post</div>
      </div>
        <div id="posts">
          <div class="row">
          <%@posts.each do |post|%>
                <div class="col lg-4">
                  <%= render partial:"posts/post",locals:{post:post}%>
                </div>
          <%end%>
          </div>
        </div>
  </div>
</div>
<script>
      var myModal = document.getElementById('exampleModal')
      myModal.hidden= true
</script>
<style>
  .post_img {
    width: 200px;
    height: 200px;
    object-fit: cover;
    border-radius: 50%;
    float: right;
    top:20px;
  }
  .main{
    margin-top: 40px;
  }
  #info
  {
    margin-left: 40px;
    margin-bottom: 50px;
  }
  #posts
  {
    display: flex;
    justify-content: space-between;
  }
  #archived
  {
    margin-left: 30px;
    width: max-content;
    margin-right: 30px;
  }
  #createPost
  {
    width: max-content;
  }

</style>

app/views/profiles/new.html.erb
<div class="main">
    <div class="container">
        <h1>Create New Profile</h1>
            <div id="createProfile">
                <%=form_with model: @profile do |form| %>
                <%=form.label :user_name%>
                <%=form.text_field :user_name%>
                <%=form.label :profile_picture%>
                <%=form.file_field :profile_picture%>
                <%=form.submit%>
                 <%end%>
            </div>
    </div>
</div>

app/views/profiles/search.html.erb
<div class="main">
  <div class="container">
    <div class="search">
    <h1>Results</h1>
      <div id="result">
          <%@result.each do |user|%>
            <%=image_tag user.profile_picture.representation(resize_to_limit: [250, 250]),id: "searchResult"%>
            <%=link_to "#{user.user_name}",profile_path(user),class: "btn btn primary"%>
          <%end%>
      </div>
  </div>
  </div>
</div>
<style>
    .main
    {
      margin-top: 40px;
    }
    #result
    {
      margin-bottom: 10px;
    }
</style>

app/views/profiles/show.html.erb
<div class="main">
  <div class="container">
   <%=image_tag @profile.profile_picture.representation(resize_to_limit: [250, 250]),class: "post_img"%>
    <h1><%=@profile.user_name%></h1>
        <div id="info">
          <%=link_to "Followers: #{@followers}",new_post_path,data:{turbo_frame: "modal"},class:"btn btn primary"%>
          <%=link_to "Following: #{@following}",new_post_path,data:{turbo_frame: "modal"},class:"btn btn primary"%>
          <%# <span>Posts: <span id="postCount"><%=@post_count</span> </span>%>
          <%if @has_followed==1%>
            <%=link_to "Unfollow",friendships_unfollow_profile_path(@profile.id),class:"btn btn-primary"%>
          <% else %>
            <%=link_to "Follow",friendships_follow_profile_path(@profile.id),class:"btn btn-primary"%>
          <% end %>
        </div>
        <% if @profile.status=="public_profile" %>
            <div class="row pb-2">
                <%@posts.each do |post|%>
                <div class="col lg-3">
                  <div class="eachImage">
                    <%if post.images.attached?%>
                        <%if  post.images.first.content_type.include?("image")%>
                        <%if post.images.count>1%>
                            <div id="Carousel<%=post.id%>" class="carousel slide" data-bs-ride="carousel">
                            <!-- Wrapper for slides -->
                            <div class="carousel-inner">
                              <% post.images.each_with_index do |image, index| %>
                                <div class="carousel-item <%= 'active' if index == 0 %>">
                                  <%= image_tag image.representation(resize_to_limit: [400, 400]), id: "oneImg",class:"img" ,:"data-postId" => post.id ,alt: "Slide #{index + 1}"%>
                                </div>
                              <% end %>
                            </div>

                            <!-- Left and right controls -->
                          <button class="carousel-control-prev" type="button" data-bs-target="#Carousel<%=post.id%>" data-bs-slide="prev">
                              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                              <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next next" type="button" data-bs-target="#Carousel<%=post.id%>" data-bs-slide="next">
                              <span class="carousel-control-next-icon" aria-hidden="true"></span>
                              <span class="visually-hidden">Next</span>
                            </button>
                          </div>
                          <%else%>

                        <div class="image-container">
                          <% post.images.each do |image| %>
                            <%= image_tag image.representation(resize_to_limit: [400, 400]), id: "oneImg",class:"img", :"data-postId" => post.id %>
                          <% end %>
                        </div>

                          <%end%>
                        <% else %>
                          <%=video_tag url_for(post.images.first),controls: true,width: "400",height: "auto",id:"oneVideo" ,class:"img" ,:"data-postId"=>post.id%>
                        <% end %>
                      <%end%>
                  </div>
                  <div>
                    <p>"<%=post.caption%>" Location: <%=post.location%></p>
                  </div>
                   <%if post.status=="shared"%>
                              <%if !(post.shared.include?current_account.email)%>

                                  <p class="mb-2">Post By:<%=post.shared%><span class="badge rounded-pill text-bg-success">Shared</span></p>

                            <%else%>
                                 <p>You Shared This Post</p>
                            <%end%>
                    <%end%>
                  <%=link_to "Likes",post_likes_path(post),data:{turbo_frame: "likes"},class:"btn btn primary"%>
                  <%=link_to "Comments",post_comments_path(post),data:{turbo_frame: "postComments"},class:"btn btn primary"%>
                   <%if !(post.likes.find_by(email:current_account.email))%>
                        <%= render partial: "likes/likes",locals:{my_post:post}%>
                    <%else%>
                        <%= render partial: "likes/unlike",locals:{my_post:post}%>
                    <%end%>
                  <%=link_to "Share",share_post_path(post),data:{turbo_method: :post},id:"commentBtn" ,class:"btn btn-primary"%>
                  <%=link_to "Comment",new_post_comment_path(post),data:{turbo_frame: "comment"},id:"commentBtn" ,class:"btn btn-primary"%>
                </div>
              <%end%>
            </div>
          <%elsif @profile.status=="private_profile" && @has_followed==1%>
              <div class="row">
                <%@posts.each do |post|%>
                <div class="col lg-3">
                  <div class="eachImage">
                    <%if post.images.attached?%>
                        <%if  post.images.first.content_type.include?("image")%>
                        <%if post.images.count>1%>
                            <div id="Carousel<%=post.id%>" class="carousel slide" data-bs-ride="carousel">
                            <!-- Wrapper for slides -->
                            <div class="carousel-inner">
                              <% post.images.each_with_index do |image, index| %>
                                <div class="carousel-item <%= 'active' if index == 0 %>">
                                  <%= image_tag image.representation(resize_to_limit: [400, 400]), id: "oneImg",class:"img" ,:"data-postId" => post.id ,alt: "Slide #{index + 1}"%>
                                </div>
                              <% end %>
                            </div>

                            <!-- Left and right controls -->
                          <button class="carousel-control-prev" type="button" data-bs-target="#Carousel<%=post.id%>" data-bs-slide="prev">
                              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                              <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next next" type="button" data-bs-target="#Carousel<%=post.id%>" data-bs-slide="next">
                              <span class="carousel-control-next-icon" aria-hidden="true"></span>
                              <span class="visually-hidden">Next</span>
                            </button>
                          </div>
                          <%else%>

                        <div class="image-container">
                          <% post.images.each do |image| %>
                            <%= image_tag image.representation(resize_to_limit: [400, 400]), id: "oneImg",class:"img", :"data-postId" => post.id %>
                          <% end %>
                        </div>

                          <%end%>
                        <% else %>
                          <%=video_tag url_for(post.images.first),controls: true,width: "400",height: "auto",id:"oneVideo" ,class:"img" ,:"data-postId"=>post.id%>
                        <% end %>
                      <%end%>
                  </div>
                  <div>
                    <p>"<%=post.caption%>" Location: <%=post.location%></p>
                  </div>
                   <%if post.status=="shared"%>
                              <%if !(post.shared.include?current_account.email)%>

                                  <p>Post By:<%=post.shared%><span class="badge rounded-pill text-bg-success">Shared</span></p>

                            <%else%>
                                 <p>You Shared This Post</p>
                            <%end%>
                    <%end%>
                  <%=link_to "Likes",post_likes_path(post),data:{turbo_frame: "likes"},class:"btn btn primary"%>
                  <%=link_to "Comments",post_comments_path(post),data:{turbo_frame: "postComments"},class:"btn btn primary"%>
                   <%if !(post.likes.find_by(email:current_account.email))%>
                        <%= render partial: "likes/likes",locals:{my_post:post}%>
                    <%else%>
                        <%= render partial: "likes/unlike",locals:{my_post:post}%>
                    <%end%>
                  <%=link_to "Share",share_post_path(post),data:{turbo_method: :post},id:"commentBtn" ,class:"btn btn-primary"%>
                  <%=link_to "Comment",new_post_comment_path(post),data:{turbo_frame: "comment"},id:"commentBtn" ,class:"btn btn-primary"%>
                </div>
              <%end%>
            </div>
          <%else%>
          <div id="message">
              <h1><%=@message%></h1>
          </div>
        <% end %>
  </div>
</div>
<style>
  .post_img {
    width: 200px;
    height: 200px;
    object-fit: cover;
    border-radius: 50%;
    float: right;
    top:20px;
  }
  .main{
    margin-top: 40px;
  }
  #info
  {
    margin-left: -15px;
    margin-bottom: 50px;
  }
  #message
  {
    text-align: center;
  }
  .posts
  {
    padding: 20px;
    display: flex;
    justify-content: space-between;
  }
  #oneVideo
  {
    margin: 10px;
  }
</style>