config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :accounts, controllers: {
    sessions: 'accounts/sessions',
    passwords: 'accounts/passwords',
    registrations: 'accounts/registrations',
    confirmations: 'accounts/confirmations'

  }
  namespace :admins do
    get '/', to: 'admins#index'
    get 'status', to: 'admins#status'
    post 'de_activate/:account_id', to: 'admins#de_activate', as: :admins_de_activate
    post 'activate/:account_id', to: 'admins#activate', as: :admins_activate
  end

  get 'accounts/confirmation_pending', to: 'profiles#after_registration_path'
  get 'accounts/after_confirmation', to: 'profiles#after_confirmation_path'
  post 'profiles/search', to: 'profiles#search'
  get 'profiles/status', to: 'profiles#change_status'
  root to: 'homes#index'
  resources :profiles, only: %i[new create index edit show update] do
    member do
      get '/friendships/follow', to: 'friendships#follow'
      get 'friendships/unfollow', to: 'friendships#unfollow'
    end
  end
  get '/archives', to: "posts#archives"
  resources :posts, only: %i[new create edit update] do
    member do
      post '/share', to: 'posts#share'
      get '/archive_post', to: 'posts#archive_post'
      get '/un_archive_post', to: 'posts#un_archive_post'
      post '/likes/un_like', to: 'likes#un_like'
      post 'likes/like', to: 'likes#like'
    end
    resources :comments, :likes, shallow: true
  end
  delete '/posts/destroy', to: 'posts#destroy'
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord

  enum archived: { true: 1 ,false: 0 }
  enum status: { shared: 1, shared_not: 0}

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many_attached :images

end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  include CurrentProfile
  include ProfilePicture
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params.merge(profile_id: current_profile))
    if @post.save
      @postcount = Post.all.count
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.prepend('posts', partial: 'posts/post', locals: { post: @post }) }
        format.html { redirect_to profiles_path, notice: 'Post Created' }
      end
    else
      render :new, status: :unporocessable_entity
    end
  end

  def destroy
    @post = Post.find_by(id: params[:post_id])
    @post.destroy
    respond_to(&:js)
  end

  def edit
    @post = Post.find_by(id: params[:id])
  end

  def update
    @post = Post.find_by(id: params[:id])
    @post.update(edit_params)
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.replace("onePost-#{@post.id}", partial: 'posts/post', locals: { post: @post }) }
      format.html { redirect_to profiles_path, notice: 'Post Created' }
    end
  end

  def share
    post = Post.find_by(id:params[:id])
    share_post = post.dup
    share_post.update(comment_count:0,likes_count:0,profile_id:current_profile,shared:Profile.where(id:post.profile_id).pluck(:user_name),status:1,images:post.images_blobs)
  end

  def archives
    @archives = Post.where(archived:1)
    @current_profile = Profile.find_by(id:current_profile)
    @current_profile_picture = current_profile_picture
  end

  def archive_post
    Post.find_by(id:params[:id]).true!
    redirect_to profiles_path
  end

  def un_archive_post
    Post.find_by(id:params[:id]).false!
    redirect_to archives_path
  end

  private

  def post_params
    params.require(:post).permit(:caption, :location, images: [])
  end

  def edit_params
    params.require(:post).permit(:caption, :location)
  end
end

app/views/posts/_post.html.erb
<div class="post" id="onePost-<%=post.id%>">
  <div>
    <%if post.images.attached?%>
      <%if  post.images.first.content_type.include?("image")%>
      <%if post.images.count>1%>
          <div id="Carousel<%=post.id%>" class="carousel slide" data-bs-ride="carousel">
          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <% post.images.each_with_index do |image, index| %>
              <div class="carousel-item <%= 'active' if index == 0 %>">
                 <%= image_tag image.representation(resize_to_limit: [400, 400]), id: "oneImg",class:"img" ,:"data-postId" => post.id ,alt: "Slide #{index + 1}"%>
              </div>
            <% end %>
          </div>

          <!-- Left and right controls -->
         <button class="carousel-control-prev" type="button" data-bs-target="#Carousel<%=post.id%>" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next next" type="button" data-bs-target="#Carousel<%=post.id%>" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
        <%else%>

      <div class="image-container">
        <% post.images.each do |image| %>
          <%= image_tag image.representation(resize_to_limit: [400, 400]), id: "oneImg",class:"img", :"data-postId" => post.id %>
        <% end %>
      </div>

        <%end%>
      <% else %>
        <%=video_tag url_for(post.images.first),controls: true,width: "400",height: "auto",id:"oneVideo" ,class:"img" ,:"data-postId"=>post.id%>
      <% end %>
    <%end%>
  </div>
  <div>
    <p>"<%=post.caption%>" Location: <%=post.location%></p>
  </div>
  <div>
       <%if post.status=="shared"%>
            <p>Post By:<%=post.shared%><span class="badge rounded-pill text-bg-success">Shared</span></p>
        <%end%>
      <%=link_to "Likes",post_likes_path(post),data:{turbo_frame: "likes"},class:"btn btn primary"%>
      <%=link_to "Comments",post_comments_path(post),data:{turbo_frame: "postComments"},class:"btn btn primary"%>
      <%=link_to "Archive Post",archive_post_post_path(post),data:{turbo_method: :get},class:"btn btn-outline-danger"%>
  </div>
</div>
<style>
  .post
  {
    padding: 20px;
  }
  .next
  {
    left: 300px;
  }
</style>
<script>
      //open a modal with edit and delete by clicking on any post
      var myModal = document.getElementById('exampleModal')
      a=document.getElementsByClassName("img")
      myModal.hidden= true
      Object.keys(a).forEach((x)=>{a[x].addEventListener('click',(e)=>{
          myModal.hidden= false
          b=a[x].dataset.postid
          var token = document.getElementsByName('csrf-token')[0].content
          const btn=document.getElementById("deleteBtn")
          btn.addEventListener('click',()=>{
            $.ajax({
                  url: '/posts/destroy',
                  method: 'DELETE',
                  data: {post_id: b},
                  headers: {
                    'X-CSRF-Token': token,
                  },
                  success: function(data){

                  }
            })
          })
          const editBtn=document.getElementById("editBtn")
          const editPost=document.getElementById("editPost")
          editPost.hidden=true
          editBtn.addEventListener('click',(e)=>{
            editPost.hidden=false
            editPost.click()
            editPost.setAttribute("href","/posts/"+b+"/edit")
          })
      })})

       $(document).ready(function() {
        $('.carousel').carousel();
        console.log("Carousel initialization script executed.");
      });
      // window.onclick = function(event) {
      //     if (event.target.id != "exampleModal" && event.target.id != "oneImg" && event.target.id != "editBtn") {
      //           myModal.hidden= true
      //     }
      //   }
  </script>

app/views/posts/archives.html.erb
<div class="main">
  <div class="container">
    <h1>ARCHIVES</h1>
    <div>
        <%@archives.each do |post|%>
            <div id="archives">
                <%=link_to "#{@current_profile.user_name}",profile_path(@current_profile.id),class:"btn btn primary"%>
               <%if post.images.attached?%>
                    <%if  post.images.first.content_type.include?("image")%>
                    <%if post.images.count>1%>
                        <div id="Carousel<%=post.id%>" class="carousel slide" data-bs-ride="carousel">
                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                          <% post.images.each_with_index do |image, index| %>
                            <div class="carousel-item <%= 'active' if index == 0 %>">
                              <%= image_tag image.representation(resize_to_limit: [400, 400]), id: "oneImg",class:"img" ,:"data-postId" => post.id ,alt: "Slide #{index + 1}"%>
                            </div>
                          <% end %>
                        </div>

                        <!-- Left and right controls -->
                      <button class="carousel-control-prev" type="button" data-bs-target="#Carousel<%=post.id%>" data-bs-slide="prev">
                          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                          <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next next" type="button" data-bs-target="#Carousel<%=post.id%>" data-bs-slide="next">
                          <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="visually-hidden">Next</span>
                        </button>
                      </div>
                      <%else%>

                    <div class="image-container">
                      <% post.images.each do |image| %>
                        <%= image_tag image.representation(resize_to_limit: [400, 400]), id: "oneImg",class:"img", :"data-postId" => post.id %>
                      <% end %>
                    </div>

                      <%end%>
                    <% else %>
                      <%=video_tag url_for(post.images.first),controls: true,width: "400",height: "auto",id:"oneVideo" ,class:"img" ,:"data-postId"=>post.id%>
                    <% end %>
                  <%end%>
                <%=post.caption%>
                <%=post.location%>
               <%=link_to "Un Archive",un_archive_post_post_path(post),data:{turbo_method: :get},class:"btn btn-outline-success"%>
            </div>
          <%end%>
        </div>
  </div>
</div>
<style>
  .post_img {
    width: 200px;
    height: 200px;
    object-fit: cover;
    border-radius: 50%;
    float: right;
    top:20px;
  }
  #archives
  {
    padding: 20px;
  }
  .main{
    margin-top: 40px;
  }
</style>

app/views/posts/destroy.js.erb
$("#onePost-<%=params[:post_id]%>").remove();

app/views/posts/edit.html.erb
<%=turbo_frame_tag "editModal" do%>
  <div class="editModal">
    <div>
       <h3>Edit Post</h3>
      <%=form_with model: @post do |form|%>
        <div class="field">
           <%=form.label :caption%>
           <%=form.text_field :caption ,class: 'form-control'%>
        </div>
        <div class="field">
          <%=form.label :location%>
           <%=form.text_field :location ,class: 'form-control'%>
        </div>
        <div class="submit">
          <%=form.submit class:"btn btn-primary" %>
        </div>
      <%end%>
    </div>
    <div>
       <%=link_to "Close","#",data:{
      controller: "edit-modal",
      action: "edit-modal#close"
    },class:"btn btn-secondary"%>
    </div>
  </div>
<%end%>

app/views/posts/new.html.erb
<%=turbo_frame_tag "modal" do%>
  <div class="modal">
    <div>
       <h3>Create a post</h3>
      <%=form_with model: @post do |form|%>
        <div class="field">
           <%=form.label :caption%>
           <%=form.text_field :caption ,class: 'form-control'%>
        </div>
        <div class="field">
          <%=form.label :location%>
           <%=form.text_field :location ,class: 'form-control'%>
        </div>
        <div class="field">
           <%=form.label :images%>
            <%=form.file_field :images,:multiple => true ,class: 'form-control'%>
        </div>
        <div class="submit">
          <%=form.submit class:"btn btn-primary" %>
        </div>
      <%end%>
    </div>
    <div>
       <%=link_to "Close","#",data:{
      controller: "modals",
      action: "modals#close"
    },class:"btn btn-secondary"%>
    </div>
  </div>
<%end%>